sudo: false

language: python

python:
 - "2.7"

notifications:
  email:
    on_failure: change

install:
  - conda create env --name remotesensingenv -f conda_reqs.txt
  - source activate remotesensingenv
  - pip install -r pip_reqs.txt

script: python setup.py test