sudo: false

language: python

python:
 - "2.7"

notifications:
  email:
    on_failure: change


env:
  # Default values for common packages, override as needed
  global:
    - PYTHON=2.7


before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes --quite conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Build package list to avoid empty package=versions; only needed for versioned pacakges
  - PKGS="python=${PYTHON}"
  - PKGS="${PKGS} numpy"; if [ ${NUMPY} ]; then PKGS="${PKGS}=${NUMPY}"; fi
  - PKGS="${PKGS} pip";

install:
  - conda create --yes --quiet -n pychron-test ${PKGS} ${OPTIONAL}
  - source activate pychron-test
  - conda install --yes --file requirements_tests.txt
  - pip install uncertainties

script: python setup.py test